CREATE DATABASE IF NOT EXISTS BASHPROJECT;

USE BASHPROJECT;

CREATE TABLE IF NOT EXISTS ACCOUNTS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	SALT VARCHAR(200) NOT NULL
);
CREATE TABLE IF NOT EXISTS MEALS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50),
	CUSTOMER_ID INT,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES ACCOUNTS(ID)
);
